
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Mar 07 23:51:53 COT 2022
//----------------------------------------------------

package controllers;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int IGUALDAD = 5;
  public static final int VARIABLEY = 10;
  public static final int SUMA = 2;
  public static final int VARIABLEX = 9;
  public static final int ERROR = 14;
  public static final int PALABRA_RESERVADA = 13;
  public static final int EOF = 0;
  public static final int NUMERO_NEGATIVO = 8;
  public static final int SEPARADOR = 6;
  public static final int NUMERO_POSITIVO = 7;
  public static final int error = 1;
  public static final int ASIGNACION = 4;
  public static final int ECUACION2 = 12;
  public static final int RESTA = 3;
  public static final int ECUACION1 = 11;
}

